### ISSUE TITLE
Language does not update on selecting Infographics/Videos

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanOnline-v2#122] opened 2021-08-31 18:16 UTC
From notes/highlights /bookmarks page, on opening a book and chapter eg Telugu John1 and then switching to  a different language (say Hindi John1), the language does not update on selecting Infographics and Videos. ie on switching from  Telugu John 1 to Hindi John1, the content on infographics  and video does not refresh. 
Note: This does not happen on selecting language directly from Book selector (noted on production site also)-

**Comment by AnnCherianA** [comment] 2021-08-31 18:17
![image](https://user-images.githubusercontent.com/74647279/131555221-3ef740b3-ab29-438d-b32e-73661e58e7eb.png)

**Comment by AnnCherianA** [comment] 2021-09-10 17:54
![image](https://user-images.githubusercontent.com/74647279/132896754-6c9e574b-938c-4776-b637-1963729225aa.png)

**Comment by JesniJ** [comment] 2022-07-06 09:14
Completed testing and the issue is fixed . The language is updating when navigating through notes , videos and infographics. As discussed moving this issue to done.

**Closed** 2022-10-17 10:53 UTC
Labels: bug
